# Generated by Django 5.1.1 on 2024-09-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_cart_companyinfo_picture_alter_client_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('local_create_date', models.DateTimeField(auto_now=True)),
                ('local_update_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('link', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
