# Generated by Django 5.1.1 on 2024-09-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_sponsor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='link',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='picture',
            field=models.ImageField(default='', upload_to='banners'),
        ),
    ]
