# Generated by Django 5.1.1 on 2024-09-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_remove_sponsor_link_sponsor_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='sponsors',
            field=models.ManyToManyField(help_text='select sponsors for this company', to='entities.sponsor'),
        ),
    ]
